---
kind: pipeline
name: docker build/push
type: docker

trigger:
  branch:
    - master
  event:
    exclude:
      - promote
      - rollback

steps:
  - name: build and push docker
    image: plugins/docker
    settings:
      username: "austin1howard"
      password:
        from_secret: dockerhub_token
      repo: austin1howard/jot-backend
      tags:
        - latest
        - git-${DRONE_COMMIT_SHA:0:8}
      squash: true
      cache_from:
        - austin1howard/jot-backend:latest